// Copyright Shiba Inu Games LLC.

#pragma once

#include "CoreMinimal.h"
#include "GameFramework/PlayerState.h"
#include "ShibBasePlayerState.generated.h"

class UShibGameInstance;
class AShibBaseGameMode;
class AShibCharacter;
class AShibBaseController;

/**
 * 
 */
UCLASS()
class SHIBRUN_API AShibBasePlayerState : public APlayerState
{
	GENERATED_BODY()

public:
	AShibBasePlayerState();

	// Setup custom replicated variables
	virtual void GetLifetimeReplicatedProps(TArray< FLifetimeProperty >& OutLifetimeProps) const override;
	
	/**
	* Load the selected class from the Game Instance when we join a new session.
	* This should be only used one time when we join a new session.
	* This is used by the ShibLobbyController class
	*/
	UFUNCTION(BlueprintCallable, Client, Reliable)
	void Client_LoadSelectedShibClassFromInstance();
	
	/**
	* Set the selected shib class
	* This can be called on clients or server
	* It always handles the class selection on the server side.
	*/
	UFUNCTION(BlueprintCallable)
	virtual void SetSelectedShibClass(EShibClass NewShibClass);

	// Shib backend user ID used for getting and sending player data through the Shib APIs
	// this is different from the UniqueNetID generated by Unreal, and shouldn't be used to identify the player within the game
	UPROPERTY(Replicated, BlueprintReadWrite, Category = "PlayerStateInfo")
	int32 CachedShibUserId = -1;
	
	// Selected character class
	UPROPERTY(Replicated, BlueprintReadWrite, Category = "PlayerStateInfo")
	EShibClass SelectedShibClass;

	UPROPERTY(BlueprintReadWrite, Category = "PlayerStateInfo")
	FName CheckpointTag = FName();

protected:
	/**
	* Copy the player's info from the original player state to the newly create one after a server travel. 
	* This is called by default by the engine once the player moved to another map using the same player state class. 
	* Other default values are also copied in the parent's function, see parent class function 
	*/ 
	virtual void CopyProperties(APlayerState* PlayerState) override;

	/**
	* Server function to share the cached shib user id with the server
	* this is used by the server to transfer player data and stats using the Shib APIs
	*/
	UFUNCTION(Server, Reliable, WithValidation, BlueprintCallable)
	void Server_ShareShibUserId(int32 ShibUserId);
	
	/**
	* Server function caller to set the Selected class
	*/																																	  												
	UFUNCTION(Server, Reliable, BlueprintCallable)
	void Server_SetSelectedShibClass(EShibClass NewShibClass);
	
	/**
	* Getters
	*/
	UPROPERTY()
	TObjectPtr<UShibGameInstance> ShibGI;
	TObjectPtr<UShibGameInstance> GetShibGI();
	
	UPROPERTY()
	TObjectPtr<AShibBaseController> ShibCtrl;
	TObjectPtr<AShibBaseController> GetShibCtrl();
	
	UPROPERTY()
	TObjectPtr<AShibCharacter> ShibCharacter;
	TObjectPtr<AShibCharacter> GetShibCharacter();
	
	UPROPERTY()
	TObjectPtr<AShibBaseGameMode> ShibBaseGM;
	TObjectPtr<AShibBaseGameMode> GetShibBaseGM();

};
